// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD14aSmLrR7dbimRAX8o_Z-qZjF6P7FX1o',
    appId: '1:1004636433134:android:ea66ff316bc008395ce1ff',
    messagingSenderId: '1004636433134',
    projectId: 'gmp-dev-19352',
    storageBucket: 'gmp-dev-19352.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS0fpkb1XTlGVA3RCIpCtaOMIP_us9lf8',
    appId: '1:1004636433134:ios:fccc428cfe97d7645ce1ff',
    messagingSenderId: '1004636433134',
    projectId: 'gmp-dev-19352',
    storageBucket: 'gmp-dev-19352.appspot.com',
    androidClientId: '1004636433134-7ajlch14g5utlr8lt6koe245pci21lec.apps.googleusercontent.com',
    iosClientId: '1004636433134-95okedktcu0bvr36q181ot81fkmb9u96.apps.googleusercontent.com',
    iosBundleId: 'com.ethicaldigit.gmp',
  );
}
